{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": 
      [
        "rekognition:DetectLabels",
        "dynamodb:UpdateItem",
        "lambda:InvokeFunction"
      ],
      "Effect": 
        "Allow",
      "Sid": 
        "",
      "Resource":
        "*"
    },
    {
      "Action":
        "s3:ListBucket",
      "Effect": 
        "Allow",
      "Resource":
        "arn:aws:s3:::${bucket}"
    },
    {
      "Action": 
        "s3:GetObject",
      "Effect": 
        "Allow",
      "Resource":    
        "arn:aws:s3:::${bucket}/*"
    }
  ]
}